# Generated by Django 5.0.7 on 2024-12-16 21:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(default='NOMINADO', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MediaPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_media', models.CharField(choices=[('LOCAL', 'Archivo Local'), ('YOUTUBE', 'Video de YouTube')], default='LOCAL', max_length=10)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='pregunta/medias', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg', 'mp4'])])),
                ('youtube_url', models.URLField(blank=True, help_text='Ingresa la URL del video de YouTube', null=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='core.pregunta')),
            ],
        ),
    ]
