# Generated by Django 5.0.7 on 2024-12-16 21:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(default='NOMINADO', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='estado',
        ),
        migrations.AlterField(
            model_name='mediapregunta',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='Opciones/medias', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg', 'mp4'])]),
        ),
        migrations.AlterField(
            model_name='mediapregunta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='core.opciones'),
        ),
    ]
