# Generated by Django 5.0.7 on 2024-12-17 21:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_opciones_pregunta_alter_opciones_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_media', models.CharField(choices=[('LOCAL', 'Archivo Local'), ('YOUTUBE', 'YouTube')], default='LOCAL', max_length=10)),
                ('archivo', models.FileField(blank=True, help_text='Subir archivos de imagen, video (mp4) o SVG', null=True, upload_to='media/')),
                ('url_youtube', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='opciones',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='nombre',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='pregunta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='encuesta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='core.encuesta'),
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(max_length=200)),
                ('medias', models.ManyToManyField(blank=True, related_name='opciones', to='core.media')),
                ('pregunta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='core.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_twitch', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('pregunta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pregunta')),
                ('opcion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.opcion')),
            ],
        ),
        migrations.DeleteModel(
            name='MediaPregunta',
        ),
        migrations.DeleteModel(
            name='Opciones',
        ),
    ]
