# Generated by Django 5.0.7 on 2024-12-17 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_encuesta_media_remove_opciones_pregunta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='ip_address',
        ),
    ]
