# Generated by Django 5.0.7 on 2024-12-18 02:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_formulario_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='color',
            field=models.CharField(blank=True, default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', message='El color debe ser un código hexadecimal válido.')]),
        ),
        migrations.AddField(
            model_name='opcion',
            name='color',
            field=models.CharField(blank=True, default='#28a745', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', message='El color debe ser un código hexadecimal válido.')]),
        ),
        migrations.AlterField(
            model_name='media',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
