# Generated by Django 5.0.7 on 2024-12-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_formulario_color_opcion_color_alter_media_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='color',
        ),
        migrations.AddField(
            model_name='formulario',
            name='fecha_votacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='nombre_twitch',
            field=models.CharField(max_length=100),
        ),
    ]
