# Generated by Django 5.0.7 on 2024-12-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_formulario_color_formulario_fecha_votacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='nombre_twitch',
        ),
        migrations.AlterField(
            model_name='opcion',
            name='medias',
            field=models.ManyToManyField(blank=True, related_name='opciones_media', to='core.media'),
        ),
    ]
