# Generated by Django 5.0.7 on 2024-12-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_formulario_nombre_twitch_alter_opcion_medias'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='nombre_twitch',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
