# Generated by Django 5.0.7 on 2024-12-22 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_formulario_nombre_twitch'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='pregunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='core.pregunta'),
        ),
    ]
