# Generated by Django 5.2.1 on 2025-12-08 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_media_pregunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='streamer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='encuesta',
            name='streamer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encuestas', to='core.streamer'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='streamer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formularios', to='core.streamer'),
        ),
        migrations.AddField(
            model_name='media',
            name='streamer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='core.streamer'),
        ),
        migrations.AddField(
            model_name='opcion',
            name='streamer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='core.streamer'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='streamer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='core.streamer'),
        ),
    ]
