# Generated by Django 5.2.1 on 2025-12-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_streamer_encuesta_streamer_formulario_streamer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('TERMINADA', 'Terminada')], default='ACTIVA', max_length=10),
        ),
    ]
