# Generated by Django 5.2.1 on 2025-12-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_encuesta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora para terminar la encuesta automáticamente.', null=True),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora para activar la encuesta automáticamente.', null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('TERMINADA', 'Terminada'), ('PROGRAMADA', 'Programada')], default='ACTIVA', max_length=10),
        ),
    ]
