# Generated by Django 5.2.1 on 2025-12-15 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_encuesta_fecha_fin_encuesta_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='streamer',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='streamer',
        ),
        migrations.RemoveField(
            model_name='media',
            name='streamer',
        ),
        migrations.RemoveField(
            model_name='opcion',
            name='streamer',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='streamer',
        ),
        migrations.DeleteModel(
            name='streamer',
        ),
    ]
