# Generated by Django 5.2.1 on 2025-12-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_pregunta_streamer_remove_encuesta_streamer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
